test_queries = [

#  FACTUAL (16)
("What is photosynthesis?", "factual"),
("Who is Mahatma Gandhi?", "factual"),
("When was India independent?", "factual"),
("What is RAM?", "factual"),
("Define machine learning", "factual"),
("What is blockchain?", "factual"),
("Who invented the telephone?", "factual"),
("What is CPU?", "factual"),
("Define gravity", "factual"),
("What is HTTP?", "factual"),
("Who is Elon Musk?", "factual"),
("What is Python programming?", "factual"),
("What is GDP?", "factual"),
("Define cloud computing", "factual"),
("What is data science?", "factual"),
("What is neural network?", "factual"),

# 🔹 COMPARATIVE (16)
("Compare AI and ML", "comparative"),
("Difference between RAM and ROM", "comparative"),
("Python vs Java", "comparative"),
("Advantages of solar vs wind energy", "comparative"),
("Compare HTTP and HTTPS", "comparative"),
("Difference between TCP and UDP", "comparative"),
("Which is better Python or C++?", "comparative"),
("Compare supervised and unsupervised learning", "comparative"),
("Pros and cons of electric cars", "comparative"),
("Difference between AI and deep learning", "comparative"),
("Compare Android and iOS", "comparative"),
("Advantages of online vs offline learning", "comparative"),
("Difference between SQL and NoSQL", "comparative"),
("Compare cloud and edge computing", "comparative"),
("Which is better laptop or tablet?", "comparative"),
("Compare data mining and data analysis", "comparative"),

#  RELATIONAL (16)
("How does inflation affect economy?", "relational"),
("Relationship between DNA and RNA", "relational"),
("How does climate change affect rainfall?", "relational"),
("Impact of social media on mental health", "relational"),
("How does exercise affect heart health?", "relational"),
("Relationship between supply and demand", "relational"),
("How does AI impact jobs?", "relational"),
("Effect of pollution on environment", "relational"),
("How does stress affect the brain?", "relational"),
("Relationship between education and income", "relational"),
("How does internet affect communication?", "relational"),
("Impact of technology on society", "relational"),
("How does sleep affect productivity?", "relational"),
("Effect of caffeine on body", "relational"),
("How does global warming affect oceans?", "relational"),
("Relationship between marketing and sales", "relational"),

#  EXPLORATORY (16)
("Explain machine learning", "exploratory"),
("Overview of artificial intelligence", "exploratory"),
("Explain climate change", "exploratory"),
("How does the internet work?", "exploratory"),
("Explain blockchain technology", "exploratory"),
("Describe human digestive system", "exploratory"),
("Explain quantum computing", "exploratory"),
("Overview of data science", "exploratory"),
("Explain cloud computing", "exploratory"),
("How does neural network work?", "exploratory"),
("Explain big data", "exploratory"),
("Describe software development lifecycle", "exploratory"),
("Explain cybersecurity basics", "exploratory"),
("Overview of IoT", "exploratory"),
("Explain database management systems", "exploratory"),
("How does operating system work?", "exploratory"),

#  NO RETRIEVAL (16)
("What is 2+2?", "no_retrieval"),
("Define AI in one word", "no_retrieval"),
("What does CPU stand for?", "no_retrieval"),
("What is 10% of 200?", "no_retrieval"),
("Convert 5 km to meters", "no_retrieval"),
("What is the square of 5?", "no_retrieval"),
("Define RAM in one sentence", "no_retrieval"),
("What is 100 divided by 4?", "no_retrieval"),
("What is the formula of area of circle?", "no_retrieval"),
("What does HTTP stand for?", "no_retrieval"),
("What is 15+20?", "no_retrieval"),
("Define data in one sentence", "no_retrieval"),
("What is 50% of 300?", "no_retrieval"),
("What is the value of pi?", "no_retrieval"),
("Convert 1 hour to minutes", "no_retrieval"),
("What is 7 times 8?", "no_retrieval"),
]